spring:
  profiles:
    active:
    - local
---
spring:
  config:
    activate:
      on-profile: local #이클립스 내에서 돌릴때.
      
  rabbitmq:
    host: 127.0.0.1

---
spring:
  config:
    activate:
      on-profile: prod
      
  rabbitmq:
    host: ems-rabbitmq
      
---
server:
  tomcat:
    basedir: /usr/local/tomcat/logs/
    accesslog:
      enabled: true
      directory: ${spring.application.name}
      prefix: access_log.
      suffix: .txt
      #rotate: true
      file-date-format: yy-MM-dd #yy-MM-dd.HH
      #encoding: UTF-8
      #max-days: -1
      #rename-on-rotate: false
      #buffered: false
      #condition-if: name #ServletRequest.getAttribute("name") != null
      #condition-unless: name #ServletRequest.getAttribute("name") == null
      pattern: '%h %l %u [%{yy-MM-dd:HH:mm:ss}t] "%r" %s %b %D %{User-Agent}i' #'%h %l %u %t "%r" %s %b'
  port: 8761 #애플리케이션의 서버 포트
  
spring:
  application:
    name: ems-discovery-service # 애플리케이션의 이름
  rabbitmq:  # rabbitmq을 이용하기 위한 정보 설정
    port: 5672 # RabbitMQ 포트번호
    username: guest # RabbitMQ 서버연결시 사용자 이름과 pw
    password: guest
    
    
eureka:
  client:
    register-with-eureka: false # Eureka (디스커버리)에 등록여부
    fetch-registry: false   # 다른 인스턴스(서비스)에게 데이터를 제공할꺼냐? ㄴㄴ
       # 유레카서버(=디스커버리서버)로부터 다른인스턴스(서비스)들의 정보를 가져와서 갱신할꺼냐?

       
management:
  endpoints:
    web:
      exposure:  # endpoints노출 설정
        include: refresh, health, beans, busrefresh 
        # 애플리케이션의 refresh(재로드), health(상태확인), beans(빈정보), busrefresh(분산환경에서 메세지 버스를 통해 설정 변경갱신)