server:
  port: 0 # 0번 port를 사용하겠다는 의가 아님. 사용되지 않는 port번호를 임의로 할당해달라는 의미...
  
spring:
  application:
    name: order-service
    
  h2: # h2 데이터베이스 설정
    console:
      enabled: true # 브라우저에에서 콘솔을 볼 수 있게 하겠다.
      settings:
        web-allow-others: true
      path: /h2-console # url
      
  jpa:
    defer-datasource-initialization: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
      
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true # 유레카 서버에 등록
    fetch-registry: true # 주기적으로 다른 인스턴스의 데이터를 받아와서 갱신
    service-url:
      defaultZone: http://localhost:8761/eureka # 유레카 서버의 주소 정보

